version: "3.7"

services:
  vncorenlp:
    build: .
    expose:
      - "9000"
  nginx:
    image: nginx:1.19.6
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vncorenlp
    ports:
      - "8000:80"